service: musify-server

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  environment:
    spotifyClientId: ${env:SPOTIFY_CLIENT_ID}
    spotifyClientSecret: ${env:SPOTIFY_CLIENT_SECRET}
  apiGateway:
    minimumCompressionSize: 1024

custom:
  customDomain:
    domainName: api.tunesfer.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false

functions:
  getPlaylist:
    handler: playlist.getPlaylist
    events:
      - http:
          path: playlist/{id}
          method: get
          cors: true
